server:
  port: 8080

spring:
  datasource:
    username: dbuser
    password: password
    url: jdbc:ch://localhost:8123/clickhousedb

exchangerate:
  api-url: https://api.exchangerate-api.com/v4/latest/
  enabled: true
  cron: 0 0 * * * *

moex:
  api-url: https://iss.moex.com/iss/engines/stock/markets/%s/securities.json?iss.meta=off&iss.only=securities&securities.columns=SECID,PREVPRICE

exchange:
  enabled: true
  cron: 0 0 * * * *
  source:
    stock: SHARES/boards/TQBR
    etf: SHARES/boards/TQTF
    ofz: BONDS/boards/TQOB
    bound: BONDS/boards/TQCB